/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.ude.poo.radioypublicidadUDC.vistas;

/**
 *
 * @author thalma
 */
public class vistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form vistaPrincipal
     */
    public vistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        todoElmenu = new javax.swing.JMenuBar();
        menuEmisora = new javax.swing.JMenu();
        agregar_emisora = new javax.swing.JMenuItem();
        Consultar = new javax.swing.JMenuItem();
        editar_emisora = new javax.swing.JMenuItem();
        eliminar_emisora = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuEmpresa = new javax.swing.JMenu();
        consultar_nombre_del_director = new javax.swing.JMenuItem();
        direccion_postal = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        direccion_postal1 = new javax.swing.JMenuItem();
        menuPo_radio = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        nombre_del_programa = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        menuCadenaRadio = new javax.swing.JMenu();
        nombre_Representativo = new javax.swing.JMenuItem();
        nombreCadena = new javax.swing.JMenuItem();
        eliminarCadenadeRadio = new javax.swing.JMenuItem();
        menuPatrocinadores = new javax.swing.JMenu();
        nombre_patrocinador = new javax.swing.JMenuItem();
        eliminarPatrocinadores = new javax.swing.JMenuItem();

        jPanel1.setBackground(new java.awt.Color(204, 0, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(153, 0, 153))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 255));

        menuEmisora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/Radioypublicidad/vistas/iconos/emisora32px.png"))); // NOI18N
        menuEmisora.setText("Emisora");
        menuEmisora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmisoraActionPerformed(evt);
            }
        });

        agregar_emisora.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        agregar_emisora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/Radioypublicidad/vistas/iconos/agregar24px.png"))); // NOI18N
        agregar_emisora.setText("agregar");
        agregar_emisora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_emisoraActionPerformed(evt);
            }
        });
        menuEmisora.add(agregar_emisora);

        Consultar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/Radioypublicidad/vistas/iconos/consulta24px.png"))); // NOI18N
        Consultar.setText("consultar emisora...");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        menuEmisora.add(Consultar);

        editar_emisora.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editar_emisora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/Radioypublicidad/vistas/iconos/editar24px.png"))); // NOI18N
        editar_emisora.setText("editar emisora");
        editar_emisora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar_emisoraActionPerformed(evt);
            }
        });
        menuEmisora.add(editar_emisora);

        eliminar_emisora.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eliminar_emisora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/Radioypublicidad/vistas/iconos/eliminare24px.png"))); // NOI18N
        eliminar_emisora.setText("eliminar...");
        eliminar_emisora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_emisoraActionPerformed(evt);
            }
        });
        menuEmisora.add(eliminar_emisora);
        menuEmisora.add(jSeparator1);

        todoElmenu.add(menuEmisora);

        menuEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/Radioypublicidad/vistas/iconos/ empresa24px.png"))); // NOI18N
        menuEmpresa.setText("Empresa");

        consultar_nombre_del_director.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        consultar_nombre_del_director.setText("consultar nombre del director");
        consultar_nombre_del_director.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_nombre_del_directorActionPerformed(evt);
            }
        });
        menuEmpresa.add(consultar_nombre_del_director);

        direccion_postal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        direccion_postal.setText("consultar direccion postal");
        direccion_postal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccion_postalActionPerformed(evt);
            }
        });
        menuEmpresa.add(direccion_postal);
        menuEmpresa.add(jSeparator2);

        direccion_postal1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        direccion_postal1.setText("consultar direccion postal");
        direccion_postal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccion_postal1ActionPerformed(evt);
            }
        });
        menuEmpresa.add(direccion_postal1);

        todoElmenu.add(menuEmpresa);

        menuPo_radio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/Radioypublicidad/vistas/iconos/programaRadio24px.png"))); // NOI18N
        menuPo_radio.setText("Programa de radio");

        jMenuItem13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem13.setText("franjas horarias");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        menuPo_radio.add(jMenuItem13);

        nombre_del_programa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nombre_del_programa.setText("nombre del programa");
        menuPo_radio.add(nombre_del_programa);

        jMenuItem15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem15.setText("nombre del responsable");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        menuPo_radio.add(jMenuItem15);

        todoElmenu.add(menuPo_radio);

        menuCadenaRadio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/Radioypublicidad/vistas/iconos/cadenadeRadio24px.png"))); // NOI18N
        menuCadenaRadio.setText("Cadena de radio");

        nombre_Representativo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nombre_Representativo.setText(" nombre respresentativo");
        nombre_Representativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_RepresentativoActionPerformed(evt);
            }
        });
        menuCadenaRadio.add(nombre_Representativo);

        nombreCadena.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nombreCadena.setText("nombre de cadena");
        nombreCadena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreCadenaActionPerformed(evt);
            }
        });
        menuCadenaRadio.add(nombreCadena);

        eliminarCadenadeRadio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eliminarCadenadeRadio.setText("eliminar...");
        eliminarCadenadeRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarCadenadeRadioActionPerformed(evt);
            }
        });
        menuCadenaRadio.add(eliminarCadenadeRadio);

        todoElmenu.add(menuCadenaRadio);

        menuPatrocinadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/Radioypublicidad/vistas/iconos/patrocinadores24px.png"))); // NOI18N
        menuPatrocinadores.setText("Patrocinadores");

        nombre_patrocinador.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nombre_patrocinador.setText("nombre del patrocinador");
        nombre_patrocinador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_patrocinadorActionPerformed(evt);
            }
        });
        menuPatrocinadores.add(nombre_patrocinador);

        eliminarPatrocinadores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eliminarPatrocinadores.setText("eliminar...");
        eliminarPatrocinadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarPatrocinadoresActionPerformed(evt);
            }
        });
        menuPatrocinadores.add(eliminarPatrocinadores);

        todoElmenu.add(menuPatrocinadores);

        setJMenuBar(todoElmenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregar_emisoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_emisoraActionPerformed
        vistaUsuarios vistas = new vistaUsuarios (this, true);
        vistas.setLocationRelativeTo(this);
        vistas.setVisible(true);

    }//GEN-LAST:event_agregar_emisoraActionPerformed

    private void editar_emisoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar_emisoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editar_emisoraActionPerformed

    private void eliminar_emisoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_emisoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar_emisoraActionPerformed

    private void consultar_nombre_del_directorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_nombre_del_directorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultar_nombre_del_directorActionPerformed

    private void direccion_postalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccion_postalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccion_postalActionPerformed

    private void direccion_postal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccion_postal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccion_postal1ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void nombre_patrocinadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_patrocinadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_patrocinadorActionPerformed

    private void eliminarPatrocinadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarPatrocinadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarPatrocinadoresActionPerformed

    private void nombre_RepresentativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_RepresentativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_RepresentativoActionPerformed

    private void nombreCadenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreCadenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreCadenaActionPerformed

    private void eliminarCadenadeRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarCadenadeRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarCadenadeRadioActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        agregar_emisoraActionPerformed(evt);
    }//GEN-LAST:event_ConsultarActionPerformed

    private void menuEmisoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmisoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuEmisoraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new vistaPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Consultar;
    private javax.swing.JMenuItem agregar_emisora;
    private javax.swing.JMenuItem consultar_nombre_del_director;
    private javax.swing.JMenuItem direccion_postal;
    private javax.swing.JMenuItem direccion_postal1;
    private javax.swing.JMenuItem editar_emisora;
    private javax.swing.JMenuItem eliminarCadenadeRadio;
    private javax.swing.JMenuItem eliminarPatrocinadores;
    private javax.swing.JMenuItem eliminar_emisora;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu menuCadenaRadio;
    private javax.swing.JMenu menuEmisora;
    private javax.swing.JMenu menuEmpresa;
    private javax.swing.JMenu menuPatrocinadores;
    private javax.swing.JMenu menuPo_radio;
    private javax.swing.JMenuItem nombreCadena;
    private javax.swing.JMenuItem nombre_Representativo;
    private javax.swing.JMenuItem nombre_del_programa;
    private javax.swing.JMenuItem nombre_patrocinador;
    private javax.swing.JMenuBar todoElmenu;
    // End of variables declaration//GEN-END:variables
}
